// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyDoN4D_s5meGotmYEBA0rdg2UK6cw5Dvd4",
  authDomain: "website-portfolio-cc307.firebaseapp.com",
  projectId: "website-portfolio-cc307",
  storageBucket: "website-portfolio-cc307.appspot.com",
  messagingSenderId: "613918209038",
  appId: "1:613918209038:web:72611519fdf06e988cb85f",
  measurementId: "G-Q17EYPRELF"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);
